Error: File: Ex95_faceRecognition.m Line: 127 Column: 56
Error: File: Ex95_faceRecognition.m Line: 127 Column: 56
Invalid expression. Check for missing or extra characters.